name: my_dbt_project
profile: all
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
    +file_format: delta
    +location_root: |
      {{ "/mnt/gold/" ~ target.schema ~ "/analytics" }}
