# dbt_project.yml
name: analytics
profile: all
version: "1.0.0"

models:
  analytics:
    +materialized: table
# flags:
#   warn_error_options:
#     silence:
#       - DeprecationsSummary
#       # - MissingArgumentsPropertyInGenericTestDeprecation
