name: my_dbt_project
profile: all
version: "1.0.0"

clean-targets:
   - target
   - target_old
   - dbt_packages

models:
   my_dbt_project:
    +materialized: table

tests:
   +store_failures: true
   +database: "{{ target.name | upper }}_JYEO"

# target.name's are 'development' or 'prod'.
