name: my_jaffle_shop
profile: all
config-version: 2
version: "1.0.0"

models:
 my_jaffle_shop:
   +materialized: table

# We will have a YAML schema validation warning. But this doesn't stop the config from working.
saved-queries:
  my_jaffle_shop:
    +schema: dbt_jyeo_saved_queries 

# dbt-cloud:
#     project-id: 370817
