name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table
    mart:
      +schema: dev
      +database: development_jyeo
    stage:
      +schema: dev
      +database: test_jyeo
    int:
      +schema: dev
      int_a:
        +database: int_a
      int_b:
        +database: int_b
      int_c:
        +database: int_c
      int_d:
        +database: int_d
      int_e:
        +database: int_e

# Schema 'int_a.dev' has 5000 dummy tables with 50 columns each = 250,000
# Schema 'int_b.dev' has 5000 dummy tables with 50 columns each = 250,000
# Schema 'int_c.dev' has 5000 dummy tables with 50 columns each = 250,000
# Schema 'int_d.dev' has 5000 dummy tables with 50 columns each = 250,000
# Schema 'int_e.dev' has 5000 dummy tables with 50 columns each = 250,000
