name: my_dbt_project
profile: databricks
config-version: 2
version: 1.0

seeds:
  my_dbt_project:
    +file_format: delta
    +location_root: /mnt/root/seeds
    +persist_docs:
      relation: true
      columns: true
