name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
    my_dbt_project:
        materialized: table
        schema: dev
    marts:
        materialized: view

sources:
    my_dbt_project:
        enabled: true

