# dbt_project.yml
name: my_dbt_project
profile: all
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table 

on-run-start: "{% do log(env_var('DBT_ENV', 'Env var DBT_ENV is not set'), True) %}"
