name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
    folder_foo:
      +enabled: "{{ var('enable_foo', false) | as_bool }}"
    folder_bar:
      +enabled: true
