models:
  - name: foo
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: int
        constraints:
          - type: not_null
    versions:
      - v: 1
        deprecation_date: 1970-01-01
