groups:
  - name: finance
    owner:
      # Email is required to receive model-level notifications, additional properties are also allowed.
      name: "Finance team"
      email: jeremyyeodbt@proton.me
  - name: marketing
    owner:
      name: "Marketing team"
      email: jeremyyeodbt@proton.me

models:
  - name: foo
    columns:
      - name: id
        tests:
          - not_null
    config:
      group: finance
  - name: bar
    columns:
      - name: id
        tests:
          - not_null
    config:
      group: marketing
