sources:
  - name: raw
    tables:
      - name: customers
        config:
          freshness:
            error_after: { count: 12, period: hour }
          loaded_at_field: updated_at
      - name: orders
        config:
          freshness:
            error_after: { count: 12, period: hour }
          loaded_at_field: updated_at
