
sources:
  - name: dbt_jyeo
    loaded_at_field: created_date
    tables:
      - name: raw_customers
        freshness: 
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        
