version: 2
sources:
  - name: raw
    database: staging
    schema: dbt_jyeo
    loader: S3
    tables:
      - name: ext_people
        external:
          location: '@dbt_test.dbt_external_tables_integration_tests_snowflake.dbt_external_tables_testing/parquet'
          file_format: 'dbt_test.dbt_external_tables_integration_tests_snowflake.dbt_external_tables_testing_parquet'
          infer_schema: true
      # - name: ext_people
      #   external: &people
      #     location: "@development.dbt_jyeo.flat_files/csv"
      #     file_format: "(type = csv skip_header = 1)"
      #   columns: &people-cols
      #     - name: id
      #       data_type: int
      #     - name: first_name
      #       data_type: varchar(64)
      #     - name: last_name
      #       data_type: varchar(64)
      #     - name: email
      #       data_type: varchar(64)
      # - name: ext_people_2
      #   external: *people
      #   columns: *people-cols
